### ISSUE TITLE
Language of stemmer should be configurable

### ISSUE THREAD

**Issue by TDesjardins** [crew102/rapidrake-java#4]
Currently the language of the stemmer is hardcoded (English language):

https://github.com/crew102/rapidrake-java/blob/master/src/main/java/io/github/crew102/rapidrake/RakeAlgorithm.java#L37

The language should be configurable via RakeParams.

**Comment by crew102** [comment]
Hmm, yeah, that was an oversight. I'll try to address this sometime in the next month or so.

**Comment by TDesjardins** [comment]
I can also make a PR for this. Want only be sure that the repo is active.

**Comment by crew102** [comment]
It’s ok, I addressed it last night. Just need to clean up some code and
I’ll push

**Comment by crew102** [comment]
I'll deploy a new version to Maven tomorrow.

**Comment by TDesjardins** [comment]
LGTM. Thanks!

**Comment by crew102** [comment]
New version available on Maven Central now

**Comment by TDesjardins** [comment]
Alright, I will check this. Thanks!
